name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Cache Playwright browsers & deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers + system deps
        run: pnpm exec playwright install --with-deps

      - name: Run all tests (Node + Browser)
        run: xvfb-run -a pnpm test:all

  benchmarks:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g pnpm

      - name: Restore caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-ci-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers + system deps
        run: pnpm exec playwright install --with-deps

      - name: Clean previous benchmarks
        run: rm -f node-benchmarks.json browser-benchmarks.json

      - name: Run Node benchmarks
        run: pnpm vitest bench --run --project=node --outputFile=node-benchmarks.json

      - name: Run Browser benchmarks
        run: xvfb-run -a pnpm vitest bench --run --project=browser --outputFile=browser-benchmarks.json

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            node-benchmarks.json
            browser-benchmarks.json

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g pnpm

      - name: Restore pnpm store cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Verify build artifacts
        run: |
          echo "Verifying build artifacts:"
          ls -lh dist
          [ -f dist/index.js ]   || (echo "❌ Missing index.js"   && exit 1)
          [ -f dist/index.mjs ]  || (echo "❌ Missing index.mjs"  && exit 1)
          [ -f dist/index.d.ts ] || (echo "❌ Missing index.d.ts" && exit 1)
