name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    if: ${{ secrets.NPM_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 10.13.1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Create GitHub Release and Publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm publish --no-git-checks --access public
          commit: "chore(release): publish"
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
